### ISSUE TITLE
Add masscanned

### ISSUE THREAD

**Issue by p-l-** [paralax/awesome-honeypots#96]
Hi there,

[I am the author of IVRE and a contributor to masscanned]

I think [masscanned](https://github.com/ivre/masscanned) could have its place here!

It is a low-interaction honeypot dedicated to scanners observation. It is similar to Masscan in that it has a userland, minimalist network stack. If Masscan is a client, masscanned is a server.

Even though masscanned can be used on its own, it can also be used together with [IVRE](https://github.com/ivre/ivre) to build a self-hosted alternative to services such as Greynoise, so maybe IVRE could be listed in the "Data Tools" section.

All the best,

Pierre

**Comment by paralax** [comment]
sounds good, can you send in a PR?

**Comment by p-l-** [comment]
Yep, sure!
